apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: go-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
